name: Terraform Apply

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 3: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 4: Terraform Plan
      - name: Terraform Plan
        run: terraform plan